In [1]:
import numpy as np

RED_PLAYER = 'r'
BLUE_PLAYER = 'b'
PLAYERS = [RED_PLAYER, BLUE_PLAYER]
WIN_CONDITIONS = ["Horizontal", "Vertical", "Diagonally Ascending", "Diagonally Descending"]



#TODO TIE CONDITION!

class Field:
    """
    Connect4 Field represented as a list of lists.
    """

    def __init__(self, x=7, y=5):
        """
        Initalize the playing field
        :param x: # columns
        :param y: # rows
        """
        assert x > 0 and y > 0, "X and Y must be greater than 0!"
        self.x = x
        self.y = y

        self.field = None
        self.new_field()

    def place_piece(self, x, player):
        """
        Places a piece in the given column by the given player.
        :param x: column index
        :param player: player string
        :return: False if invalid column (full or otherwise), 'Valid' if successful, 1 if win condition achieved
        """
        assert player in [RED_PLAYER, BLUE_PLAYER], "Invalid player ID!"
        # Check for a tie
        if all(self.field):
            return 2
        try:
            x = int(x)
            column = self.field[x]
        except (IndexError, ValueError):
            print("Not a valid column!")
            return False
        if all(column) != 0:
            print("Full!")
            return False
        column[column.index(0)] = player
        self.field[x] = column
        if self.check_for_winner(player):
            return 1
        return 'Valid'

    def _check_for_four(self, potential):
        """
        Checks a boolean list for 4 consecutive Trues
        :param potential: boolean list
        :return: True if four consecutive Trues exist
        """
        return True if (True, True, True, True) in zip(potential, potential[1:], potential[2:],
                                                       potential[3:]) else False

    def _straight_check(self, bool_field):
        """
        Check across a straight line for the win condition
        :param bool_field: boolean field where True is where the player's pieces are
        :return: True if win, False if not
        """
        values = []
        for potential in bool_field:
            values.append(self._check_for_four(potential))
        if True in values:
            return True
        return False

    def _diagonal_check(self, bool_field):
        """
        Check across a diagonal line for the win condition
        :param bool_field: boolean field where True is where the player's pieces are
        :return: True if win, False if not
        """
        values = []
        for potential_index in range(-self.x + 1, self.y):
            potential = bool_field.diagonal(potential_index)
            values.append(self._check_for_four(potential))
        if True in values:
            return True
        return False

    def check_for_winner(self, player):
        """
        Checks for all four win conditions for the given player
        :param player: player string
        :return: True if win, False if not
        """
        field = np.array(self.field)
        field = field == player

        checks = []
        # Check for all four winning conditions.  Keep these in this order!
        checks.append(self._straight_check(field.T))
        checks.append(self._straight_check(field))
        checks.append(self._diagonal_check(field))
        checks.append(self._diagonal_check(np.fliplr(field)))

        finder = [True if check is True else False for check in checks]
        for i, win_condition in enumerate(finder):
            if win_condition == True:
                print("Win Condition Met: {}".format(WIN_CONDITIONS[i]))
                return True
        return False

    def new_field(self):
        """Resets field"""
        self.field = [[0] * self.y for _ in range(self.x)]

    @property
    def raw_display(self):
        """Internal representation"""
        return self.field

    @property
    def debug_display(self):
        """Array representation"""
        return np.flipud(np.array(self.field).T)


def play(field):
    done = False
    print(field.debug_display)
    while True:
        for player in PLAYERS:
            result = False
            while not result:
                move = input("Where do you want to move, Player {}?: ".format(player))
                result = field.place_piece(move, player)
            print(field.debug_display)
            if result == 1:
                print("Player {} WINS!".format(player))
                done = True
            elif result ==2:
                print("Tie!")
                done = True
            if done: break
        if done: break


if __name__ == '__main__':
    play(Field())

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Where do you want to move, Player r?: 1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Tie!


f = Field()

In [ ]:
f.play()

# 

In [ ]:
f=Field()
f.field
f.place_piece(1, 'r')
f.place_piece(1, 'b')

In [ ]:
f.debug_display

In [ ]:
f.place_piece(1, 'b')
f.debug_display

In [ ]:
f.raw_display

In [ ]:
t= f.check_for_winner()

In [ ]:
for i in t:
    print(i)

In [ ]:
for i in t:
    print(True if (True, True, True, True) in zip(i, i[1:], i[2:], i[3:]) else False)
# x for x, y in zip(a, a[1:]) if x == y}

In [ ]:
t= np.random.random((5,10))
print(t)
print(t.T)
for i in range(-5, 10):
    print(t.diagonal(i), i)